apiVersion: v2
name: infra-guardian
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"


dependencies:
  - name: kube-prometheus-stack
    version: "55.5.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
