apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-guardian
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-guardian
  template:
    metadata:
      labels:
        app: infra-guardian
    spec:
      serviceAccountName: infra-guardian-sa
      containers:
        - name: infra-guardian
          image: sagarbawanthade/infra-guardian:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: ALERTS_ENABLED
              value: "true"

            - name: ALERT_COOLDOWN_MINUTES
              value: "15"

            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: infra-guardian-secrets
                  key: SLACK_WEBHOOK_URL

            - name: PROM_URL
              value: "http://monitoring-kube-prometheus-prometheus.default:9090"
              
